name: Deploy Backend
on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      
      - name: Build and Push
        id: meta
        run: |
          TAG="us-central1-docker.pkg.dev/${{ vars.PROJECT_ID }}/worknoon-repo/backend:${{ github.sha }}"
          docker build -t $TAG ./backend
          docker push $TAG
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  trigger-infra:
    needs: build-backend
    uses: ./.github/workflows/terraform-apply.yml
    with:
      backend_image: ${{ needs.build-backend.outputs.tag }}
      frontend_image: 'use-active-state'
    secrets: inherit